import type {
  Allocation,
  Attributes,
  Catalog,
  EnemyDefinition,
  EnemyMove,
  ItemDefinition,
  QuestDefinition,
  Requirements,
  TechniqueDefinition,
} from "@/game/types";
import { legacyCatalog as legacy } from "./legacy-catalog";

const attrs = (
  strength: number,
  defense: number,
  speed: number,
  endurance: number,
  kiControl = strength,
): Attributes => ({ strength, defense, speed, endurance, kiControl });
const affinity = (
  primary: keyof Allocation,
  secondary: keyof Allocation,
  a = 1.25,
  b = 1.1,
): Allocation => ({
  strength: 1,
  defense: 1,
  speed: 1,
  endurance: 1,
  kiControl: 1,
  [primary]: a,
  [secondary]: b,
});
const flag = (id: string): Requirements => ({ flags: [`quest:${id}`] });
const hit = (label: string, techniqueId = "soco", multiplier = 1): EnemyMove => ({
  kind: "attack",
  label,
  techniqueId,
  multiplier,
});
const guard: EnemyMove = { kind: "guard", label: "Assume uma postura defensiva" };
const charge: EnemyMove = { kind: "charge", label: "Concentra energia: prepare sua defesa!" };
const poison: EnemyMove = {
  kind: "attack",
  label: "Prepara um golpe venenoso",
  techniqueId: "soco",
  status: "poison",
};
const patterns = {
  basic: [hit("Avança para atacar"), hit("Prepara um golpe forte", "chute", 1.1), guard],
  beast: [hit("Prepara uma mordida"), charge, hit("Vai investir com toda a força", "chute", 1.8)],
  martial: [
    hit("Prepara um golpe técnico", "chute"),
    guard,
    charge,
    hit("Prepara uma investida poderosa", "jan-ken", 1.3),
  ],
  ki: [
    hit("Prepara uma rajada", "rajada-ki"),
    guard,
    charge,
    hit("Vai disparar energia concentrada", "rajada-ki", 2),
  ],
};
function enemy(
  id: string,
  name: string,
  level: number,
  areaFlag: Requirements = {},
  pattern = patterns.basic,
  boss = false,
  artId = "soldado-red-ribbon",
): EnemyDefinition {
  const strength = Math.round(8 + level * 1.6);
  return {
    id,
    name,
    description: boss
      ? `Um desafio decisivo: observe os movimentos de ${name} e prepare seus itens.`
      : `Adversário da campanha clássica. Observe sua intenção antes de atacar.`,
    level,
    attributes: attrs(strength, 5 + level, 7 + level, 8 + level, 8 + level * 1.4),
    maxHp: Math.round(((boss ? 160 : 65) + level * (boss ? 24 : 13)) * (boss ? 1.3 : 1)),
    maxKi: 50 + level * 6,
    xpReward: boss ? 100 + level * 15 : 20 + level * 8,
    zeniReward: boss ? 50 + level * 10 : 10 + level * 3,
    boss,
    requirements: { minLevel: Math.max(1, level - (boss ? 1 : 2)), ...areaFlag },
    techniqueIds: [...new Set(pattern.flatMap((p) => (p.techniqueId ? [p.techniqueId] : [])))],
    pattern,
    phases: boss
      ? [
          {
            threshold: 0.5,
            name: `Determinação de ${name}`,
            strengthMultiplier: 1.2,
            pattern: [charge, ...pattern.filter((p) => p.kind === "attack"), guard],
          },
        ]
      : [],
    artId,
    guaranteedItem: boss ? `trofeu-${id}` : undefined,
  };
}
const equipment = (
  id: string,
  name: string,
  slot: ItemDefinition["slot"],
  effects: ItemDefinition["effects"],
  minLevel = 1,
  rarity: ItemDefinition["rarity"] = "common",
  source = "Lojas e fabricação nas vilas",
): ItemDefinition => ({
  id,
  name,
  description: source,
  slot,
  effects,
  requirements: { minLevel },
  type: "equipment",
  rarity,
  sellPrice: rarity === "epic" ? 80 : rarity === "rare" ? 35 : 12,
  source,
});
const consumable = (
  id: string,
  name: string,
  effects: ItemDefinition["effects"],
  description: string,
  rarity: ItemDefinition["rarity"] = "common",
): ItemDefinition => ({
  id,
  name,
  description,
  type: "consumable",
  rarity,
  slot: null,
  effects,
  requirements: {},
  sellPrice: rarity === "rare" ? 20 : 5,
  source: id === "semente-deuses" ? "Provas e trocas com Karin" : "Lojas, fabricação e drops",
});
const material = (
  id: string,
  name: string,
  source: string,
  rarity: ItemDefinition["rarity"] = "common",
): ItemDefinition => ({
  id,
  name,
  description: source,
  source,
  type: "material",
  rarity,
  slot: null,
  effects: {},
  requirements: {},
  sellPrice: 3,
});

const items: ItemDefinition[] = [
  consumable(
    "pocao-hp",
    "Poção de HP",
    { restoreHp: 0.35 },
    "Restaura 35% do HP. Usar em batalha ocupa uma ação.",
  ),
  consumable("pocao-hp-forte", "Poção de HP forte", { restoreHp: 0.6 }, "Restaura 60% do HP."),
  consumable("pocao-ki", "Poção de Ki", { restoreKi: 0.3 }, "Restaura 30% do Ki."),
  consumable("pocao-ki-forte", "Poção de Ki forte", { restoreKi: 0.55 }, "Restaura 55% do Ki."),
  consumable("antidoto", "Antídoto", { cure: ["poison"] }, "Remove veneno. Não restaura HP."),
  consumable(
    "tonico-foco",
    "Tônico de concentração",
    { kiDamageBuff: 0.15 },
    "+15% de dano de Ki por três rodadas.",
  ),
  consumable(
    "semente-deuses",
    "Semente dos Deuses",
    { restoreHp: 1, restoreKi: 1, cure: ["poison", "paralysis", "armor-break"] },
    "Restaura HP e Ki e remove efeitos. Uma por batalha.",
    "rare",
  ),
  consumable(
    "refeicao",
    "Refeição preparada",
    { restoreHp: 0.8, restoreKi: 0.5, outsideOnly: true },
    "Comida de vila. Recupera 80% de HP e 50% de Ki fora da batalha.",
  ),
  equipment("bastao", "Bastão", "weapon", { attributes: { strength: 4 } }),
  equipment(
    "luvas-combate",
    "Luvas de combate",
    "weapon",
    { attributes: { strength: 3 }, guardBreak: 0.15 },
    3,
  ),
  equipment(
    "espada-deserto",
    "Espada do Deserto",
    "weapon",
    { attributes: { strength: 6, speed: 2 }, critical: 0.04 },
    5,
    "rare",
    "Yamcha: drop ou troca por 15 troféus",
  ),
  equipment(
    "bastao-magico",
    "Bastão Mágico",
    "weapon",
    { attributes: { strength: 10, speed: 3 }, guardBreak: 0.25 },
    10,
    "epic",
    "Recompensa da prova de Karin",
  ),
  equipment("armadura-simples", "Armadura simples", "armor", {
    attributes: { defense: 4, endurance: 2 },
  }),
  equipment(
    "gi-kame",
    "Gi da Escola Kame",
    "armor",
    { attributes: { endurance: 4, kiControl: 4 } },
    4,
    "uncommon",
    "Desafio de Kame ou fabricação",
  ),
  equipment(
    "traje-tsuru",
    "Traje da Escola Tsuru",
    "armor",
    { attributes: { kiControl: 9, defense: 1 } },
    15,
    "rare",
    "Tenshinhan: drop ou troca",
  ),
  equipment(
    "colete-red-ribbon",
    "Colete Red Ribbon",
    "armor",
    { attributes: { defense: 7 }, physicalResistance: 0.1 },
    8,
    "rare",
    "Muscle Tower e fabricação",
  ),
  equipment(
    "roupa-termica",
    "Roupa térmica",
    "armor",
    { attributes: { endurance: 5 }, statusResistance: 0.15 },
    7,
    "uncommon",
    "Vila Jingle",
  ),
  equipment(
    "armadura-saiyajin",
    "Armadura Saiyajin",
    "armor",
    { attributes: { defense: 10, endurance: 5 } },
    6,
    "rare",
    "Equipamento preservado da primeira versão",
  ),
  equipment("botas-leves", "Botas leves", "boots", { attributes: { speed: 4 } }),
  equipment(
    "botas-reforcadas",
    "Botas reforçadas",
    "boots",
    { attributes: { defense: 3, endurance: 2 }, physicalResistance: 0.05 },
    4,
  ),
  equipment(
    "botas-agilidade",
    "Botas de agilidade",
    "boots",
    { attributes: { speed: 6 }, evasion: 0.05 },
    8,
    "rare",
    "Ninja Murasaki: drop ou troca",
  ),
  equipment(
    "botas-karin",
    "Botas de Karin",
    "boots",
    { attributes: { speed: 7, endurance: 3 }, evasion: 0.06 },
    12,
    "rare",
    "Torre de Karin",
  ),
  equipment("faixa-foco", "Faixa de concentração", "accessory", { attributes: { kiControl: 4 } }),
  equipment(
    "braceletes",
    "Braceletes de combate",
    "accessory",
    { attributes: { strength: 3 }, critical: 0.05 },
    4,
  ),
  equipment(
    "amuleto-protecao",
    "Amuleto de proteção",
    "accessory",
    { attributes: { defense: 3 }, statusResistance: 0.25 },
    8,
    "rare",
    "General Blue: drop ou troca",
  ),
  equipment(
    "faixa-mestre",
    "Faixa do Mestre",
    "accessory",
    { attributes: { kiControl: 7, endurance: 3 }, statusResistance: 0.15 },
    17,
    "rare",
    "Jackie Chun: drop ou troca",
  ),
  material("erva", "Erva medicinal", "Lobos e bandidos da floresta"),
  material("fruto-ki", "Fruto energético", "Floresta e planícies"),
  material("couro", "Couro resistente", "Dinossauros e feras das montanhas"),
  material("presa", "Presa de dinossauro", "Dinossauros do Monte Paozu"),
  material("tecido", "Tecido reforçado", "Bandidos e soldados"),
  material("sucata", "Sucata metálica", "Robôs e soldados da Red Ribbon"),
  material("componente", "Componente Capsule Corp", "Cidade do Oeste e Caverna Pirata", "uncommon"),
  material("insignia", "Insígnia Red Ribbon", "Soldados e oficiais da Red Ribbon", "uncommon"),
];

const extraTechniques: TechniqueDefinition[] = [
  {
    id: "jan-ken",
    name: "Jan Ken",
    description: "Golpe físico que enfraquece a defesa por duas rodadas.",
    kind: "physical",
    multiplier: 1.35,
    kiCost: 8,
    cooldown: 2,
    requirements: { minLevel: 3, flags: ["quest:pilaf"] },
    learnCost: 60,
    effects: [{ kind: "status", status: "armor-break", turns: 2 }],
  },
  {
    id: "rogafufuken",
    name: "Rogafufuken",
    description: "O Punho do Lobo: golpe rápido capaz de interromper uma carga.",
    kind: "physical",
    multiplier: 1.4,
    kiCost: 15,
    cooldown: 3,
    requirements: { minLevel: 4, flags: ["quest:yamcha"] },
    learnCost: 80,
    effects: [{ kind: "interrupt" }],
  },
  {
    id: "taiyoken",
    name: "Taiyoken",
    description: "Clarão que interrompe a concentração do adversário.",
    kind: "ki",
    multiplier: 0.6,
    kiCost: 25,
    cooldown: 4,
    requirements: { minLevel: 15, flags: ["quest:chaos"] },
    learnCost: 200,
    effects: [{ kind: "interrupt" }],
  },
  {
    id: "zanzoken",
    name: "Zanzoken",
    description: "Imagem residual: +10% de esquiva por duas rodadas.",
    kind: "physical",
    multiplier: 0.9,
    kiCost: 20,
    cooldown: 3,
    requirements: { minLevel: 5, masterId: "kame" },
    learnCost: 100,
    effects: [{ kind: "evasion", amount: 0.1, turns: 2 }],
  },
  {
    id: "dodonpa",
    name: "Dodonpa",
    description: "Disparo preciso da Escola Tsuru que quebra a defesa.",
    kind: "ki",
    multiplier: 2,
    kiCost: 30,
    cooldown: 2,
    requirements: { minLevel: 15, flags: ["quest:tao"] },
    learnCost: 180,
    effects: [{ kind: "status", status: "armor-break", turns: 2 }],
  },
  {
    id: "kikohou",
    name: "Kikohou",
    description:
      "Ataque devastador. Consome também 15% do HP máximo, sem causar a própria derrota.",
    kind: "ki",
    multiplier: 2.7,
    kiCost: 45,
    hpCost: 0.15,
    cooldown: 4,
    requirements: { minLevel: 17, flags: ["quest:tenshinhan"] },
    learnCost: 250,
    effects: [{ kind: "interrupt" }],
  },
];
const techniques = [
  ...legacy.techniques.map((t) =>
    t.id === "kamehameha"
      ? { ...t, multiplier: 2.2, kiCost: 35, requirements: { minLevel: 5, masterId: "kame" } }
      : t.id === "rajada-ki"
        ? { ...t, multiplier: 1.35 }
        : t,
  ),
  ...extraTechniques,
];

const enemies: EnemyDefinition[] = [
  enemy(
    "lobo",
    "Lobo",
    1,
    {},
    [hit("Prepara uma mordida"), hit("Salta para atacar", "chute")],
    false,
    "lobo",
  ),
  enemy("bandido", "Bandido", 2, {}, patterns.basic, false, "bandido"),
  enemy("dinossauro", "Dinossauro", 3, {}, patterns.beast, false, "dinossauro"),
  enemy(
    "saibaman",
    "Saibaman · encontro extra",
    4,
    {},
    [poison, ...patterns.ki],
    false,
    "saibaman",
  ),
  enemy("soldado-red-ribbon", "Soldado da Red Ribbon", 8, flag("jackie"), patterns.ki),
  enemy(
    "piccolo-daimao",
    "Piccolo Daimao",
    20,
    { minLevel: 19, flags: ["quest:drum"] },
    [
      hit("Prepara uma rajada demoníaca", "rajada-ki"),
      guard,
      charge,
      hit("Vai devastar a arena", "kamehameha", 1.5),
    ],
    true,
    "piccolo-daimao",
  ),
  enemy("yamcha", "Yamcha", 3, flag("floresta"), patterns.martial, true, "bandido"),
  enemy("mai-shu", "Mai e Shu", 3, flag("yamcha"), patterns.ki),
  enemy(
    "pilaf",
    "Pilaf",
    4,
    flag("mai-shu"),
    [
      guard,
      hit("Aciona uma armadilha", "rajada-ki"),
      charge,
      hit("Prepara o disparo da máquina", "rajada-ki", 1.7),
    ],
    true,
  ),
  enemy(
    "prova-kame",
    "Mestre Kame · prova",
    5,
    flag("treino-kame"),
    patterns.martial,
    true,
    "bandido",
  ),
  enemy("giran", "Giran", 5, flag("prova-kame"), patterns.beast, true, "dinossauro"),
  enemy("nam", "Nam", 6, flag("giran"), patterns.martial, true, "bandido"),
  enemy(
    "jackie-chun",
    "Jackie Chun",
    7,
    flag("nam"),
    [
      guard,
      hit("Prepara um golpe veloz", "chute"),
      charge,
      hit("Concentra Kamehameha", "kamehameha", 1.3),
    ],
    true,
    "bandido",
  ),
  enemy("soldado-neve", "Soldado da torre", 8, flag("jackie"), patterns.basic),
  enemy(
    "major-metallic",
    "Major Metallic",
    9,
    flag("jingle"),
    [
      guard,
      hit("Prepara um soco metálico", "chute"),
      charge,
      hit("Aciona a arma oculta", "rajada-ki", 1.5),
    ],
    true,
  ),
  enemy(
    "murasaki",
    "Ninja Murasaki",
    9,
    flag("metallic"),
    [poison, guard, hit("Prepara uma emboscada", "chute", 1.4)],
    true,
    "bandido",
  ),
  enemy(
    "buyon",
    "Buyon",
    10,
    flag("murasaki"),
    [
      guard,
      hit("Prepara um golpe elástico", "soco"),
      poison,
      hit("Vai esmagar o adversário", "chute", 1.4),
    ],
    true,
    "dinossauro",
  ),
  enemy("general-white", "General White", 10, flag("buyon"), patterns.ki, true),
  enemy(
    "robo-pirata",
    "Robô pirata",
    11,
    flag("white"),
    [
      hit("Aciona a lâmina", "chute"),
      guard,
      charge,
      hit("Prepara o lança-chamas", "rajada-ki", 1.7),
    ],
    true,
  ),
  enemy(
    "general-blue",
    "General Blue",
    12,
    flag("pirata"),
    [
      hit("Prepara um ataque psíquico", "rajada-ki"),
      {
        kind: "attack",
        label: "Vai tentar paralisar você",
        techniqueId: "soco",
        status: "paralysis",
      },
      charge,
      hit("Vai desferir um golpe decisivo", "chute", 1.5),
    ],
    true,
  ),
  enemy(
    "prova-karin",
    "Karin · prova",
    12,
    flag("blue"),
    [
      guard,
      hit("Desafia seus reflexos", "zanzoken"),
      hit("Prepara uma investida veloz", "chute", 1.3),
    ],
    true,
    "lobo",
  ),
  enemy(
    "tao-pai-pai",
    "Tao Pai Pai",
    13,
    flag("karin"),
    [
      hit("Prepara um golpe preciso", "chute"),
      guard,
      charge,
      hit("Vai disparar Dodonpa", "dodonpa", 1.6),
    ],
    true,
    "bandido",
  ),
  enemy("oficial-red-ribbon", "Oficial Red Ribbon", 13, flag("tao"), patterns.ki),
  enemy(
    "comandante-black",
    "Comandante Black",
    14,
    flag("qg"),
    [
      guard,
      hit("Aciona o traje de batalha", "chute"),
      charge,
      hit("Prepara um disparo pesado", "rajada-ki", 2),
    ],
    true,
  ),
  enemy(
    "chaos",
    "Chaos",
    15,
    flag("black"),
    [
      hit("Concentra Dodonpa", "dodonpa"),
      guard,
      {
        kind: "attack",
        label: "Prepara uma técnica de paralisia",
        techniqueId: "soco",
        status: "paralysis",
      },
    ],
    true,
    "saibaman",
  ),
  enemy(
    "tenshinhan",
    "Tenshinhan",
    17,
    flag("chaos"),
    [
      hit("Prepara um golpe da Escola Tsuru", "chute"),
      guard,
      charge,
      hit("Vai liberar Kikohou", "kikohou", 1.3),
    ],
    true,
    "bandido",
  ),
  enemy(
    "fera-planicies",
    "Fera das planícies",
    17,
    flag("tenshinhan"),
    patterns.beast,
    false,
    "dinossauro",
  ),
  enemy("cymbal", "Cymbal", 18, flag("planicies"), [poison, ...patterns.beast], true, "dinossauro"),
  enemy("tambourine", "Tambourine", 18, flag("cymbal"), patterns.ki, true, "saibaman"),
  enemy(
    "drum",
    "Drum",
    19,
    flag("tambourine"),
    [
      guard,
      hit("Prepara uma pancada brutal", "chute"),
      charge,
      hit("Vai esmagar sua guarda", "chute", 2),
    ],
    true,
    "saibaman",
  ),
];
// Fixed heroic definitions; they never scale to the player's current level.
const heroics = enemies
  .filter((e) => e.boss && !e.id.startsWith("prova-"))
  .map((e) => ({
    ...structuredClone(e),
    id: `${e.id}-heroico`,
    name: `${e.name} · Heróico`,
    level: e.level + 4,
    attributes: Object.fromEntries(
      Object.entries(e.attributes).map(([k, v]) => [k, Math.round((v ?? 0) * 1.25)]),
    ) as Attributes,
    maxHp: Math.round(e.maxHp * 1.45),
    maxKi: Math.round(e.maxKi * 1.3),
    xpReward: Math.round(e.xpReward * 1.4),
    zeniReward: Math.round(e.zeniReward * 1.6),
    requirements: { minLevel: e.level + 2, flags: [`defeated:${e.id}`] },
    heroicOf: e.id,
    guaranteedItem: e.guaranteedItem,
  }));
for (const e of enemies.filter((e) => e.boss))
  items.push(
    material(
      `trofeu-${e.id}`,
      `Troféu: ${e.name.replace(" · prova", "")}`,
      `Garantido ao vencer ${e.name}. Troque nas vilas; 15 permitem obter um equipamento raro.`,
      "rare",
    ),
  );

const chapters: Catalog["chapters"] = [
  {
    id: "aventura",
    name: "A primeira aventura",
    description: "As trilhas de Paozu, o deserto e os planos de Pilaf.",
    order: 1,
    minLevel: 1,
    finaleQuestId: "pilaf",
    art: "floresta",
  },
  {
    id: "kame",
    name: "A Escola Kame",
    description: "Supere o treinamento e participe do 21º Tenkaichi Budokai.",
    order: 2,
    minLevel: 4,
    finaleQuestId: "jackie",
    art: "papaya",
  },
  {
    id: "norte",
    name: "A torre do norte",
    description: "Ajude Suno e liberte a Vila Jingle da Red Ribbon.",
    order: 3,
    minLevel: 7,
    finaleQuestId: "white",
    art: "jingle",
  },
  {
    id: "ribbon",
    name: "Blue, Karin e o exército",
    description: "Enfrente Blue, aprenda com Karin e alcance o QG.",
    order: 4,
    minLevel: 10,
    finaleQuestId: "black",
    art: "santuario-karin",
  },
  {
    id: "torneio",
    name: "O 22º Tenkaichi Budokai",
    description: "A Escola Tsuru testa seu domínio de combate.",
    order: 5,
    minLevel: 14,
    finaleQuestId: "tenshinhan",
    art: "papaya",
  },
  {
    id: "daimao",
    name: "O Rei Demônio",
    description: "Proteja a Terra dos guerreiros de Piccolo Daimao.",
    order: 6,
    minLevel: 17,
    finaleQuestId: "daimao",
    art: "castelo-rei",
  },
];
function quest(
  id: string,
  chapterId: string,
  name: string,
  description: string,
  requirements: Requirements,
  objectives: QuestDefinition["objectives"],
  xp: number,
  zeni: number,
  rewardItems?: { itemId: string; quantity: number }[],
  flags?: string[],
): QuestDefinition {
  return {
    id,
    chapterId,
    name,
    description,
    requirements,
    objectives,
    rewards: { xp, zeni, items: rewardItems, flags },
  };
}
const defeat = (enemyId: string, quantity = 1): QuestDefinition["objectives"][number] => ({
  kind: "defeat",
  enemyId,
  quantity,
});
const deliver = (itemId: string, quantity: number): QuestDefinition["objectives"][number] => ({
  kind: "deliver",
  itemId,
  quantity,
});
const quests: Catalog["quests"] = [
  quest(
    "floresta",
    "aventura",
    "As trilhas de Paozu",
    "Afaste dois lobos para tornar a trilha segura.",
    {},
    [defeat("lobo", 2)],
    70,
    40,
    [{ itemId: "pocao-hp", quantity: 2 }],
  ),
  quest(
    "yamcha",
    "aventura",
    "O bandido do deserto",
    "Enfrente Yamcha e aprenda a reconhecer golpes carregados.",
    flag("floresta"),
    [defeat("yamcha")],
    90,
    70,
  ),
  quest(
    "mai-shu",
    "aventura",
    "Os agentes de Pilaf",
    "Abra caminho pelas armadilhas de Mai e Shu.",
    flag("yamcha"),
    [defeat("mai-shu", 2)],
    70,
    50,
  ),
  quest(
    "pilaf",
    "aventura",
    "O castelo de Pilaf",
    "Derrote Pilaf para alcançar o treinamento da Escola Kame.",
    flag("mai-shu"),
    [defeat("pilaf")],
    120,
    100,
  ),
  quest(
    "treino-kame",
    "kame",
    "Disciplina do Mestre Kame",
    "Complete três sessões e leve quatro ervas para preparar suprimentos.",
    flag("pilaf"),
    [{ kind: "train", quantity: 3 }, deliver("erva", 4)],
    130,
    80,
  ),
  quest(
    "prova-kame",
    "kame",
    "Reconhecimento de Kame",
    "Vença a prova para aprender suas técnicas.",
    flag("treino-kame"),
    [defeat("prova-kame")],
    150,
    100,
    [{ itemId: "gi-kame", quantity: 1 }],
    ["master:kame"],
  ),
  quest(
    "giran",
    "kame",
    "A resistência de Giran",
    "Supere a força e a guarda do adversário.",
    flag("prova-kame"),
    [defeat("giran")],
    130,
    80,
  ),
  quest(
    "nam",
    "kame",
    "O salto de Nam",
    "Defenda-se de suas investidas.",
    flag("giran"),
    [defeat("nam")],
    140,
    90,
  ),
  quest(
    "jackie",
    "kame",
    "A final contra Jackie Chun",
    "Vença o primeiro torneio e abra a rota do norte.",
    flag("nam"),
    [defeat("jackie-chun")],
    220,
    150,
  ),
  quest(
    "jingle",
    "norte",
    "Suprimentos para Suno",
    "Afaste três soldados e entregue seis tecidos à vila.",
    flag("jackie"),
    [defeat("soldado-neve", 3), deliver("tecido", 6)],
    200,
    120,
    [{ itemId: "roupa-termica", quantity: 1 }],
  ),
  quest(
    "metallic",
    "norte",
    "O gigante de metal",
    "Vença Major Metallic na Muscle Tower.",
    flag("jingle"),
    [defeat("major-metallic")],
    180,
    100,
  ),
  quest(
    "murasaki",
    "norte",
    "A emboscada do ninja",
    "Leve antídotos para enfrentar Murasaki.",
    flag("metallic"),
    [defeat("murasaki")],
    190,
    110,
  ),
  quest(
    "buyon",
    "norte",
    "O monstro da torre",
    "Supere a defesa e o veneno de Buyon.",
    flag("murasaki"),
    [defeat("buyon")],
    200,
    110,
  ),
  quest(
    "white",
    "norte",
    "Libertar a Vila Jingle",
    "Derrote General White e devolva a liberdade à vila.",
    flag("buyon"),
    [defeat("general-white")],
    240,
    180,
  ),
  quest(
    "pirata",
    "ribbon",
    "A caverna dos piratas",
    "Vença o robô que protege os componentes da caverna.",
    flag("white"),
    [defeat("robo-pirata")],
    220,
    120,
  ),
  quest(
    "blue",
    "ribbon",
    "O poder de General Blue",
    "Sua paralisia exige preparo e proteção.",
    flag("pirata"),
    [defeat("general-blue")],
    230,
    130,
  ),
  quest(
    "karin",
    "ribbon",
    "Os reflexos de Karin",
    "Supere a prova na torre para dominar seu movimento.",
    flag("blue"),
    [defeat("prova-karin")],
    240,
    130,
    [
      { itemId: "bastao-magico", quantity: 1 },
      { itemId: "semente-deuses", quantity: 1 },
    ],
    ["master:karin"],
  ),
  quest(
    "tao",
    "ribbon",
    "O assassino Tao Pai Pai",
    "Use sua preparação para sobreviver a Dodonpa.",
    flag("karin"),
    [defeat("tao-pai-pai")],
    250,
    150,
  ),
  quest(
    "qg",
    "ribbon",
    "Abrir caminho até o QG",
    "Derrote três oficiais e entregue seis componentes.",
    flag("tao"),
    [defeat("oficial-red-ribbon", 3), deliver("componente", 6)],
    240,
    160,
  ),
  quest(
    "black",
    "ribbon",
    "O fim da Red Ribbon",
    "Derrote Comandante Black.",
    flag("qg"),
    [defeat("comandante-black")],
    300,
    200,
  ),
  quest(
    "chaos",
    "torneio",
    "O desafio de Chaos",
    "Supere o controle de energia da Escola Tsuru.",
    flag("black"),
    [defeat("chaos")],
    280,
    170,
  ),
  quest(
    "tenshinhan",
    "torneio",
    "A final contra Tenshinhan",
    "Reconheça o momento de defender contra Kikohou.",
    flag("chaos"),
    [defeat("tenshinhan")],
    350,
    220,
  ),
  quest(
    "planicies",
    "daimao",
    "Os suprimentos de Yajirobe",
    "Derrote três feras e reúna seis frutos energéticos.",
    flag("tenshinhan"),
    [defeat("fera-planicies", 3), deliver("fruto-ki", 6)],
    300,
    180,
  ),
  quest(
    "cymbal",
    "daimao",
    "O caçador de esferas",
    "Derrote Cymbal nas planícies.",
    flag("planicies"),
    [defeat("cymbal")],
    310,
    190,
  ),
  quest(
    "tambourine",
    "daimao",
    "A ameaça de Tambourine",
    "Impeça o ataque contra os artistas marciais.",
    flag("cymbal"),
    [defeat("tambourine")],
    320,
    200,
  ),
  quest(
    "drum",
    "daimao",
    "O último guardião",
    "Supere a força brutal de Drum.",
    flag("tambourine"),
    [defeat("drum")],
    340,
    210,
  ),
  quest(
    "daimao",
    "daimao",
    "A Terra contra Piccolo Daimao",
    "Vença o Rei Demônio e conclua a campanha clássica.",
    flag("drum"),
    [defeat("piccolo-daimao")],
    600,
    400,
    [{ itemId: "faixa-mestre", quantity: 1 }],
  ),
];
const areaRows: [string, string, string, number, Requirements, string, boolean?][] = [
  [
    "floresta",
    "Floresta do Monte Paozu",
    "Lobos, ervas e os primeiros perigos.",
    1,
    {},
    "floresta",
  ],
  [
    "montanhas",
    "Montanhas do Monte Paozu",
    "Feras, couro e presas para fabricar equipamentos.",
    2,
    {},
    "montanhas",
  ],
  [
    "deserto",
    "Deserto de Yamcha",
    "Bandidos e o temido Punho do Lobo.",
    2,
    flag("floresta"),
    "deserto",
  ],
  [
    "castelo-pilaf",
    "Castelo de Pilaf",
    "Máquinas e armadilhas de Pilaf.",
    3,
    flag("yamcha"),
    "red-ribbon",
  ],
  [
    "kame-house",
    "Kame House",
    "Treinamento, técnicas e recuperação.",
    4,
    flag("pilaf"),
    "floresta",
    true,
  ],
  [
    "papaya",
    "Ilha Papaya",
    "A arena dos torneios de artes marciais.",
    5,
    flag("prova-kame"),
    "deserto",
  ],
  [
    "jingle",
    "Vila Jingle",
    "Ajude Suno e encontre roupas e suprimentos.",
    7,
    flag("jackie"),
    "montanhas",
    true,
  ],
  [
    "muscle-tower",
    "Muscle Tower",
    "Soldados e guardiões da torre do norte.",
    8,
    flag("jackie"),
    "red-ribbon",
  ],
  [
    "cidade-oeste",
    "Cidade do Oeste",
    "Comércio e componentes da Capsule Corp.",
    10,
    flag("white"),
    "red-ribbon",
    true,
  ],
  [
    "caverna-pirata",
    "Caverna Pirata",
    "Robôs, componentes e General Blue.",
    10,
    flag("white"),
    "montanhas",
  ],
  [
    "santuario-karin",
    "Santuário de Karin",
    "O caminho para superar Tao Pai Pai.",
    11,
    flag("blue"),
    "floresta",
  ],
  [
    "torre-karin",
    "Torre de Karin",
    "Provas, recursos e Sementes dos Deuses.",
    11,
    flag("blue"),
    "montanhas",
    true,
  ],
  ["red-ribbon", "QG Red Ribbon", "Oficiais e Comandante Black.", 12, flag("tao"), "red-ribbon"],
  [
    "planicies-sul",
    "Planícies do Sul",
    "Feras e os guerreiros do Rei Demônio.",
    16,
    flag("tenshinhan"),
    "floresta",
  ],
  [
    "castelo-rei",
    "Castelo do Rei",
    "Drum e Piccolo Daimao ameaçam a Terra.",
    18,
    flag("tambourine"),
    "red-ribbon",
  ],
  [
    "encontro-extra",
    "Campo de encontros extras",
    "Saibaman: combate fora da campanha clássica.",
    3,
    {},
    "deserto",
  ],
];
const names = [
  "castelo-pilaf",
  "kame-house",
  "papaya",
  "jingle",
  "muscle-tower",
  "cidade-oeste",
  "caverna-pirata",
  "santuario-karin",
  "torre-karin",
  "planicies-sul",
  "castelo-rei",
];
const areas = areaRows.map(([id, name, description, minLevel, requirements, art, hub], order) => ({
  id,
  name,
  description,
  minLevel,
  requirements,
  art: names.includes(id) ? id : art,
  hub: hub ?? false,
  order: order + 1,
  planet: "Planeta Terra",
  color: legacy.areas.find((a) => a.id === art)?.color ?? "#f58220",
}));
const encounters = [
  ["floresta", "lobo", 3],
  ["floresta", "bandido", 2],
  ["montanhas", "dinossauro", 1],
  ["deserto", "bandido", 2],
  ["deserto", "yamcha", 1],
  ["castelo-pilaf", "mai-shu", 3],
  ["castelo-pilaf", "pilaf", 1],
  ["kame-house", "prova-kame", 1],
  ["papaya", "giran", 1],
  ["papaya", "nam", 1],
  ["papaya", "jackie-chun", 1],
  ["papaya", "chaos", 1],
  ["papaya", "tenshinhan", 1],
  ["jingle", "soldado-neve", 1],
  ["muscle-tower", "soldado-neve", 2],
  ["muscle-tower", "soldado-red-ribbon", 2],
  ["muscle-tower", "major-metallic", 1],
  ["muscle-tower", "murasaki", 1],
  ["muscle-tower", "buyon", 1],
  ["muscle-tower", "general-white", 1],
  ["caverna-pirata", "soldado-red-ribbon", 2],
  ["caverna-pirata", "robo-pirata", 1],
  ["caverna-pirata", "general-blue", 1],
  ["santuario-karin", "dinossauro", 2],
  ["santuario-karin", "tao-pai-pai", 1],
  ["torre-karin", "prova-karin", 1],
  ["red-ribbon", "oficial-red-ribbon", 3],
  ["red-ribbon", "comandante-black", 1],
  ["planicies-sul", "fera-planicies", 3],
  ["planicies-sul", "cymbal", 1],
  ["planicies-sul", "tambourine", 1],
  ["castelo-rei", "drum", 1],
  ["castelo-rei", "piccolo-daimao", 1],
  ["encontro-extra", "saibaman", 1],
].map(([areaId, enemyId, weight]) => ({
  areaId: areaId as string,
  enemyId: enemyId as string,
  weight: weight as number,
}));
const settlements: Catalog["settlements"] = [
  {
    id: "paozu",
    name: "Posto de Paozu",
    npc: "Viajante",
    description: "Suprimentos e fabricação para seus primeiros combates.",
    requirements: {},
    art: "floresta",
    respec: true,
  },
  {
    id: "kame",
    name: "Kame House",
    npc: "Mestre Kame",
    description: "Equipamentos da escola, refeições e técnicas.",
    requirements: flag("pilaf"),
    art: "kame-house",
    respec: true,
  },
  {
    id: "jingle",
    name: "Vila Jingle",
    npc: "Suno",
    description: "Tecidos, roupas e proteção para enfrentar a torre.",
    requirements: flag("jackie"),
    art: "jingle",
    respec: true,
  },
  {
    id: "oeste",
    name: "Cidade do Oeste",
    npc: "Bulma",
    description: "Componentes e equipamentos da Capsule Corp.",
    requirements: flag("white"),
    art: "cidade-oeste",
    respec: true,
  },
  {
    id: "karin",
    name: "Torre de Karin",
    npc: "Karin",
    description: "Troque os frutos de seus desafios por recursos especiais.",
    requirements: flag("karin"),
    art: "torre-karin",
    respec: true,
  },
];
const offers: Catalog["offers"] = settlements.flatMap((s) =>
  [
    ["pocao-hp", 20],
    ["pocao-ki", 25],
    ["antidoto", 15],
    ["refeicao", 30],
    ...(s.id !== "paozu"
      ? [
          ["pocao-hp-forte", 60],
          ["pocao-ki-forte", 65],
          ["tonico-foco", 40],
        ]
      : []),
    ...(s.id === "paozu"
      ? [
          ["bastao", 60],
          ["armadura-simples", 80],
          ["botas-leves", 55],
          ["faixa-foco", 55],
        ]
      : []),
    ...(s.id === "jingle" ? [["roupa-termica", 120]] : []),
  ].map(([itemId, price]) => ({
    id: `${s.id}-${itemId}`,
    settlementId: s.id,
    itemId: itemId as string,
    price: price as number,
    requirements: {},
  })),
);
const recipe = (
  id: string,
  settlementId: string,
  name: string,
  outputItemId: string,
  ingredients: [string, number][],
  zeniCost = 0,
  requirements: Requirements = {},
): Catalog["recipes"][number] => ({
  id,
  settlementId,
  name,
  outputItemId,
  outputQuantity: 1,
  ingredients: ingredients.map(([itemId, quantity]) => ({ itemId, quantity })),
  zeniCost,
  requirements,
});
const recipes: Catalog["recipes"] = [
  recipe("pocao-hp", "paozu", "Preparar Poção de HP", "pocao-hp", [["erva", 2]], 2),
  recipe("pocao-ki", "paozu", "Preparar Poção de Ki", "pocao-ki", [["fruto-ki", 2]], 2),
  recipe(
    "antidoto",
    "paozu",
    "Preparar antídoto",
    "antidoto",
    [
      ["erva", 2],
      ["fruto-ki", 1],
    ],
    2,
  ),
  recipe(
    "bastao",
    "paozu",
    "Fabricar Bastão",
    "bastao",
    [
      ["presa", 6],
      ["couro", 2],
    ],
    10,
  ),
  recipe("armadura-simples", "paozu", "Fabricar armadura", "armadura-simples", [["couro", 8]], 15),
  recipe(
    "botas-leves",
    "paozu",
    "Costurar botas",
    "botas-leves",
    [
      ["tecido", 6],
      ["couro", 2],
    ],
    10,
  ),
  recipe(
    "faixa-foco",
    "paozu",
    "Preparar faixa",
    "faixa-foco",
    [
      ["tecido", 5],
      ["fruto-ki", 3],
    ],
    10,
  ),
  recipe(
    "luvas",
    "kame",
    "Luvas de combate",
    "luvas-combate",
    [
      ["couro", 6],
      ["tecido", 4],
    ],
    20,
  ),
  recipe(
    "gi-kame",
    "kame",
    "Gi da Escola Kame",
    "gi-kame",
    [
      ["tecido", 10],
      ["fruto-ki", 4],
    ],
    25,
  ),
  recipe(
    "botas-reforcadas",
    "jingle",
    "Botas reforçadas",
    "botas-reforcadas",
    [
      ["couro", 6],
      ["sucata", 4],
    ],
    25,
  ),
  recipe(
    "colete",
    "jingle",
    "Colete Red Ribbon",
    "colete-red-ribbon",
    [
      ["sucata", 10],
      ["insignia", 5],
    ],
    30,
  ),
  recipe(
    "braceletes",
    "oeste",
    "Braceletes de combate",
    "braceletes",
    [
      ["componente", 8],
      ["sucata", 6],
    ],
    30,
  ),
  recipe(
    "hp-forte",
    "jingle",
    "Poção de HP forte",
    "pocao-hp-forte",
    [
      ["erva", 4],
      ["fruto-ki", 2],
    ],
    5,
  ),
  recipe(
    "ki-forte",
    "oeste",
    "Poção de Ki forte",
    "pocao-ki-forte",
    [
      ["fruto-ki", 4],
      ["componente", 1],
    ],
    5,
  ),
  recipe(
    "tonico",
    "oeste",
    "Tônico de concentração",
    "tonico-foco",
    [
      ["fruto-ki", 4],
      ["erva", 2],
    ],
    5,
  ),
  recipe("senzu", "karin", "Uma Semente dos Deuses", "semente-deuses", [
    ["trofeu-prova-karin", 3],
    ["fruto-ki", 6],
  ]),
  recipe("botas-karin", "karin", "Botas de Karin", "botas-karin", [["trofeu-prova-karin", 15]]),
];
const rareRewards: [string, string, string][] = [
  ["yamcha", "espada-deserto", "paozu"],
  ["pilaf", "faixa-foco", "paozu"],
  ["prova-kame", "gi-kame", "kame"],
  ["giran", "botas-reforcadas", "kame"],
  ["nam", "braceletes", "kame"],
  ["jackie-chun", "faixa-mestre", "kame"],
  ["major-metallic", "colete-red-ribbon", "jingle"],
  ["murasaki", "botas-agilidade", "jingle"],
  ["buyon", "amuleto-protecao", "jingle"],
  ["general-white", "roupa-termica", "jingle"],
  ["robo-pirata", "braceletes", "oeste"],
  ["general-blue", "amuleto-protecao", "oeste"],
  ["prova-karin", "botas-karin", "karin"],
  ["tao-pai-pai", "luvas-combate", "karin"],
  ["comandante-black", "colete-red-ribbon", "oeste"],
  ["chaos", "faixa-mestre", "karin"],
  ["tenshinhan", "traje-tsuru", "karin"],
  ["cymbal", "botas-agilidade", "karin"],
  ["tambourine", "faixa-mestre", "karin"],
  ["drum", "colete-red-ribbon", "karin"],
  ["piccolo-daimao", "traje-tsuru", "karin"],
];
for (const [bossId, itemId, settlementId] of rareRewards)
  recipes.push(
    recipe(
      `troca-${bossId}`,
      settlementId,
      `Trocar 15 troféus de ${enemies.find((e) => e.id === bossId)!.name}`,
      itemId,
      [[`trofeu-${bossId}`, 15]],
    ),
  );
const drops: Catalog["drops"] = [];
function drop(enemyId: string, itemId: string, chance: number, minQuantity = 1, maxQuantity = 1) {
  drops.push({ enemyId, itemId, chance, minQuantity, maxQuantity });
}
for (const e of [...enemies, ...heroics]) {
  const original = e.heroicOf ?? e.id;
  const military = [
    "soldado-red-ribbon",
    "soldado-neve",
    "major-metallic",
    "murasaki",
    "general-white",
    "robo-pirata",
    "general-blue",
    "oficial-red-ribbon",
    "comandante-black",
    "pilaf",
  ].includes(original);
  const mats =
    original === "lobo"
      ? ["erva", "fruto-ki"]
      : original === "bandido" || original === "mai-shu" || original === "yamcha"
        ? ["tecido", "erva"]
        : original === "dinossauro" || original === "fera-planicies"
          ? ["couro", "presa", "fruto-ki"]
          : original === "saibaman"
            ? ["fruto-ki"]
            : military
              ? ["sucata", "tecido", "componente", "insignia"]
              : ["tecido", "fruto-ki", "erva"];
  for (const id of mats) drop(e.id, id, 0.7, 1, e.boss ? 3 : 2);
  drop(e.id, "pocao-hp", 0.18);
  drop(e.id, "pocao-ki", 0.15);
  const rare = rareRewards.find(([id]) => id === original)?.[1];
  if (rare) drop(e.id, rare, e.heroicOf ? 0.1 : 0.08);
  if (e.heroicOf) drop(e.id, "bastao-magico", 0.01);
}
drop("bandido", "bastao", 0.06);
drop("dinossauro", "armadura-simples", 0.06);
drop("soldado-red-ribbon", "colete-red-ribbon", 0.02);

export const seedCatalog: Catalog = {
  races: legacy.races.map((r) => ({
    ...r,
    kiBase: 10,
    affinities:
      r.id === "saiyajin"
        ? affinity("strength", "speed")
        : r.id === "humano"
          ? affinity("speed", "kiControl", 1.2, 1.15)
          : r.id === "namekuseijin"
            ? affinity("defense", "endurance", 1.2, 1.15)
            : r.id === "majin"
              ? affinity("endurance", "defense")
              : affinity("kiControl", "speed"),
  })),
  techniques,
  items,
  areas,
  enemies: [...enemies, ...heroics].map((e) => ({ ...e, artId: e.heroicOf ?? e.id })),
  encounters,
  drops,
  chapters,
  quests,
  settlements,
  offers,
  recipes,
  policies: legacy.policies.map((p) => (p.id === "training" ? { ...p, xpReward: 10 } : p)),
  masters: [
    ...legacy.masters.map((m) => (m.id === "kame" ? { ...m, available: true } : m)),
    { id: "karin", name: "Karin", available: true },
  ],
  transformations: legacy.transformations,
};
