import type { Catalog, Attributes } from "@/game/types";
const attrs = (
  strength: number,
  defense: number,
  speed: number,
  endurance: number,
): Attributes => ({ strength, defense, speed, endurance });
export const legacyCatalog: Omit<
  Catalog,
  "chapters" | "quests" | "settlements" | "offers" | "recipes"
> = {
  trainings: [],
  races: [
    {
      id: "saiyajin",
      name: "Saiyajin",
      description:
        "Guerreiros do planeta Vegeta. Instinto de combate e força em constante evolução.",
      trait: "Força em destaque",
      color: "#f58220",
      base: attrs(12, 8, 10, 10),
      growth: attrs(3, 2, 2, 2),
    },
    {
      id: "humano",
      name: "Humano",
      description:
        "Lutadores da Terra. Técnica, agilidade e determinação para superar seus limites.",
      trait: "Velocidade em destaque",
      color: "#41a1ff",
      base: attrs(9, 9, 11, 9),
      growth: attrs(2, 2, 3, 2),
    },
    {
      id: "namekuseijin",
      name: "Namekuseijin",
      description: "Nativos de Namekusei. Resistência e defesa para enfrentar longas batalhas.",
      trait: "Defesa e resistência",
      color: "#58bc86",
      base: attrs(10, 10, 8, 12),
      growth: attrs(2, 3, 1, 3),
    },
    {
      id: "majin",
      name: "Majin",
      description:
        "Seres de poder mágico e constituição extraordinária. Uma enorme reserva de vitalidade.",
      trait: "Vitalidade em destaque",
      color: "#ed81b1",
      base: attrs(10, 9, 8, 13),
      growth: attrs(2, 2, 1, 4),
    },
    {
      id: "freeza",
      name: "Raça de Freeza",
      description:
        "Uma linhagem de poder excepcional. Força e velocidade para dominar o campo de batalha.",
      trait: "Força e velocidade",
      color: "#a18be9",
      base: attrs(11, 10, 12, 7),
      growth: attrs(3, 2, 3, 1),
    },
  ],
  policies: [
    { id: "training", durationSeconds: 30, xpReward: 50 },
    { id: "rest", durationSeconds: 30, xpReward: 0 },
    { id: "battle", durationSeconds: 5, xpReward: 0 },
  ],
  masters: [
    { id: "kame", name: "Mestre Kame", available: false },
    { id: "gohan", name: "Gohan", available: false },
    { id: "vegeta", name: "Vegeta", available: false },
  ],
  techniques: [
    {
      id: "soco",
      name: "Soco",
      description: "Um golpe direto. Sempre disponível, mesmo sem Ki.",
      kind: "physical",
      multiplier: 1,
      kiCost: 0,
      cooldown: 0,
      requirements: {},
      learnCost: 0,
      effects: [],
    },
    {
      id: "chute",
      name: "Chute",
      description: "Um golpe físico mais forte. Precisa de um turno para ser usado novamente.",
      kind: "physical",
      multiplier: 1.2,
      kiCost: 0,
      cooldown: 1,
      requirements: {},
      learnCost: 0,
      effects: [],
    },
    {
      id: "rajada-ki",
      name: "Rajada de Ki",
      description: "Concentre sua energia em uma rajada contra o inimigo.",
      kind: "ki",
      multiplier: 1.6,
      kiCost: 15,
      cooldown: 1,
      requirements: { minLevel: 2 },
      learnCost: 30,
      effects: [],
    },
    {
      id: "kamehameha",
      name: "Kamehameha",
      description: "A lendária onda de energia ensinada pelo Mestre Kame.",
      kind: "ki",
      multiplier: 3,
      kiCost: 40,
      cooldown: 3,
      requirements: { minLevel: 5, minPower: 350, masterId: "kame" },
      learnCost: 150,
      effects: [],
    },
    {
      id: "masenko",
      name: "Masenko",
      description: "Uma poderosa onda de Ki concentrada acima da cabeça.",
      kind: "ki",
      multiplier: 2.7,
      kiCost: 35,
      cooldown: 2,
      requirements: { minLevel: 6, raceIds: ["saiyajin", "namekuseijin"], masterId: "gohan" },
      learnCost: 150,
      effects: [],
    },
    {
      id: "galick-gun",
      name: "Galick Gun",
      description: "O disparo de energia característico do príncipe dos Saiyajins.",
      kind: "ki",
      multiplier: 3.2,
      kiCost: 45,
      cooldown: 3,
      requirements: { minLevel: 8, raceIds: ["saiyajin"], masterId: "vegeta" },
      learnCost: 200,
      effects: [],
    },
  ],
  items: [
    {
      id: "pocao-hp",
      name: "Poção de HP",
      description: "Recupera 50% do HP máximo. Pode ser usada após uma derrota.",
      type: "consumable",
      rarity: "common",
      slot: null,
      effects: { restoreHp: 0.5 },
      requirements: {},
    },
    {
      id: "pocao-ki",
      name: "Poção de Ki",
      description: "Recupera 50% do Ki máximo.",
      type: "consumable",
      rarity: "common",
      slot: null,
      effects: { restoreKi: 0.5 },
      requirements: {},
    },
    {
      id: "semente-deuses",
      name: "Semente dos Deuses",
      description: "Cultivada por Karin. Restaura completamente HP e Ki.",
      type: "consumable",
      rarity: "rare",
      slot: null,
      effects: { restoreHp: 1, restoreKi: 1 },
      requirements: {},
    },
    {
      id: "bastao",
      name: "Bastão",
      description: "Uma arma simples para seus primeiros combates.",
      type: "equipment",
      rarity: "common",
      slot: "weapon",
      effects: { attributes: { strength: 5 } },
      requirements: {},
    },
    {
      id: "armadura-simples",
      name: "Armadura simples",
      description: "Proteção leve para explorar a Terra.",
      type: "equipment",
      rarity: "common",
      slot: "armor",
      effects: { attributes: { defense: 5, endurance: 3 } },
      requirements: {},
    },
    {
      id: "armadura-saiyajin",
      name: "Armadura Saiyajin",
      description: "Armadura de combate resistente e flexível.",
      type: "equipment",
      rarity: "rare",
      slot: "armor",
      effects: { attributes: { defense: 10, endurance: 5 } },
      requirements: { minLevel: 6 },
    },
  ],
  areas: [
    {
      id: "floresta",
      name: "Floresta",
      description: "Trilhas selvagens, lobos e bandidos. Sua jornada começa aqui.",
      planet: "Planeta Terra",
      minLevel: 1,
      order: 1,
      color: "#4f9b78",
    },
    {
      id: "montanhas",
      name: "Montanhas",
      description: "Picos rochosos e criaturas gigantes. Cuidado com os dinossauros.",
      planet: "Planeta Terra",
      minLevel: 2,
      order: 2,
      color: "#7094b2",
    },
    {
      id: "deserto",
      name: "Deserto",
      description: "Areia, calor e estranhas criaturas de combate.",
      planet: "Planeta Terra",
      minLevel: 3,
      order: 3,
      color: "#cd9450",
    },
    {
      id: "red-ribbon",
      name: "Região da Red Ribbon",
      description: "O exército Red Ribbon controla esta região. Vença seus soldados.",
      planet: "Planeta Terra",
      minLevel: 4,
      order: 4,
      color: "#b55858",
    },
  ],
  enemies: [
    {
      id: "lobo",
      name: "Lobo",
      description: "Um predador veloz que espreita entre as árvores.",
      level: 1,
      attributes: attrs(5, 3, 7, 4),
      maxHp: 60,
      maxKi: 0,
      xpReward: 25,
      zeniReward: 10,
      boss: false,
      requirements: {},
      techniqueIds: ["soco"],
      phases: [],
    },
    {
      id: "bandido",
      name: "Bandido",
      description: "Um saqueador armado nas trilhas da floresta.",
      level: 2,
      attributes: attrs(8, 5, 6, 6),
      maxHp: 90,
      maxKi: 0,
      xpReward: 40,
      zeniReward: 20,
      boss: false,
      requirements: {},
      techniqueIds: ["chute", "soco"],
      phases: [],
    },
    {
      id: "dinossauro",
      name: "Dinossauro",
      description: "Grande, feroz e difícil de derrubar.",
      level: 3,
      attributes: attrs(13, 7, 4, 10),
      maxHp: 155,
      maxKi: 0,
      xpReward: 60,
      zeniReward: 25,
      boss: false,
      requirements: {},
      techniqueIds: ["soco"],
      phases: [],
    },
    {
      id: "saibaman",
      name: "Saibaman",
      description: "Uma criatura cultivada para lutar. Não subestime seu Ki.",
      level: 4,
      attributes: attrs(14, 10, 12, 9),
      maxHp: 170,
      maxKi: 40,
      xpReward: 80,
      zeniReward: 35,
      boss: false,
      requirements: {},
      techniqueIds: ["rajada-ki", "chute", "soco"],
      phases: [],
    },
    {
      id: "soldado-red-ribbon",
      name: "Soldado da Red Ribbon",
      description: "Um combatente treinado pelo exército Red Ribbon.",
      level: 5,
      attributes: attrs(17, 13, 13, 12),
      maxHp: 210,
      maxKi: 45,
      xpReward: 100,
      zeniReward: 45,
      boss: false,
      requirements: {},
      techniqueIds: ["rajada-ki", "chute", "soco"],
      phases: [],
    },
    {
      id: "piccolo-daimao",
      name: "Piccolo Daimao",
      description: "O Rei Demônio ameaça a Terra. Prepare-se para uma batalha decisiva.",
      level: 6,
      attributes: attrs(18, 14, 12, 15),
      maxHp: 450,
      maxKi: 60,
      xpReward: 300,
      zeniReward: 200,
      boss: true,
      requirements: { minLevel: 6, flags: ["defeated:soldado-red-ribbon"] },
      techniqueIds: ["rajada-ki", "chute", "soco"],
      phases: [{ threshold: 0.5, name: "Fúria do Rei Demônio", strengthMultiplier: 1.25 }],
    },
  ],
  encounters: [
    { areaId: "floresta", enemyId: "lobo", weight: 3 },
    { areaId: "floresta", enemyId: "bandido", weight: 2 },
    { areaId: "montanhas", enemyId: "dinossauro", weight: 1 },
    { areaId: "deserto", enemyId: "saibaman", weight: 1 },
    { areaId: "red-ribbon", enemyId: "soldado-red-ribbon", weight: 1 },
  ],
  drops: [
    { enemyId: "lobo", itemId: "pocao-hp", chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    { enemyId: "bandido", itemId: "bastao", chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    { enemyId: "bandido", itemId: "pocao-hp", chance: 0.5, minQuantity: 1, maxQuantity: 1 },
    {
      enemyId: "dinossauro",
      itemId: "armadura-simples",
      chance: 0.25,
      minQuantity: 1,
      maxQuantity: 1,
    },
    { enemyId: "dinossauro", itemId: "pocao-ki", chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    { enemyId: "saibaman", itemId: "pocao-ki", chance: 0.5, minQuantity: 1, maxQuantity: 2 },
    {
      enemyId: "soldado-red-ribbon",
      itemId: "semente-deuses",
      chance: 0.05,
      minQuantity: 1,
      maxQuantity: 1,
    },
    {
      enemyId: "soldado-red-ribbon",
      itemId: "armadura-simples",
      chance: 0.3,
      minQuantity: 1,
      maxQuantity: 1,
    },
    {
      enemyId: "piccolo-daimao",
      itemId: "semente-deuses",
      chance: 1,
      minQuantity: 1,
      maxQuantity: 2,
    },
    {
      enemyId: "piccolo-daimao",
      itemId: "armadura-saiyajin",
      chance: 0.35,
      minQuantity: 1,
      maxQuantity: 1,
    },
  ],
  transformations: [
    {
      id: "oozaru",
      name: "Oozaru",
      description: "A forma de macaco gigante dos Saiyajins.",
      multiplier: 10,
      available: false,
      requirements: {
        raceIds: ["saiyajin"],
        minLevel: 10,
        minPower: 800,
        flags: ["saiyan-tail", "full-moon-control"],
      },
    },
    {
      id: "super-saiyajin",
      name: "Super Saiyajin",
      description: "Supere os limites de um Saiyajin e desperte o lendário poder dourado.",
      multiplier: 50,
      available: false,
      requirements: {
        raceIds: ["saiyajin"],
        minLevel: 20,
        minPower: 2500,
        flags: ["saiyan-breakthrough"],
      },
    },
    {
      id: "golden-freeza",
      name: "Golden Freeza",
      description: "Uma evolução obtida por treinamento e domínio do próprio poder.",
      multiplier: 50,
      available: false,
      requirements: {
        raceIds: ["freeza"],
        minLevel: 25,
        minPower: 3500,
        flags: ["golden-mastery"],
      },
    },
  ],
};
