import type { TrainingDefinition } from "@/game/training";

export const trainingCatalog: TrainingDefinition[] = [
  {
    id: "kame-basic",
    name: "Entrega de leite",
    masterId: "kame",
    location: "Kame House",
    description: "Corrida, disciplina e entregas de leite. O primeiro passo da Escola Tartaruga.",
    artId: "kame",
    baseXpPerHour: 20,
    levelRatePercent: 3,
    requirements: {},
    order: 1,
  },
  {
    id: "kame-weights",
    name: "Casco pesado",
    masterId: "kame",
    location: "Ilha do Mestre Kame",
    description: "Leve a disciplina de Kame além do limite com o peso do casco de tartaruga.",
    artId: "kame",
    baseXpPerHour: 30,
    levelRatePercent: 4,
    requirements: {
      minLevel: 5,
      masterId: "kame",
      flags: ["quest:prova-kame", "defeated:prova-kame"],
    },
    order: 2,
  },
  {
    id: "karin",
    name: "Reflexos de Karin",
    masterId: "karin",
    location: "Torre de Karin",
    description: "Alcance a água sagrada. Karin exige velocidade, percepção e persistência.",
    artId: "karin",
    baseXpPerHour: 45,
    levelRatePercent: 6,
    requirements: {
      minLevel: 15,
      masterId: "karin",
      flags: ["quest:karin", "defeated:prova-karin"],
    },
    order: 3,
  },
  {
    id: "popo",
    name: "Silêncio e controle de Ki",
    masterId: "popo",
    location: "Templo de Kami",
    description: "Mr. Popo ensina a sentir o Ki e dominar cada movimento sem desperdiçar energia.",
    artId: "popo",
    baseXpPerHour: 60,
    levelRatePercent: 8,
    requirements: { minLevel: 25, flags: ["quest:daimao", "defeated:piccolo-daimao"] },
    order: 4,
  },
];
